# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNGameCenter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNGameCenter
  pod 'Firebase/Auth', '~> 6.30.0'

end
